### ISSUE TITLE
open to help maintaining this module?

### ISSUE THREAD

**Issue by mreinstein** [mjackson/rollup-plugin-url-resolve#11]
@mjackson would you be open to help with this module? I'm getting security alerts on outdated packages coming from this repo, and it is currently broken on windows.

I'm happy to help maintain this if that's something you'd be open to.

**Comment by mjackson** [comment]
For sure, yes. I don't currently use it in anything I'm working on, but I can imagine using it in the future so I'd like to keep it maintained if possible. I'm just really busy with other stuff right now. I'll make you a collaborator.

**Comment by mreinstein** [comment]
Thanks!

Regarding the 2 open pull requests, were you actively avoiding merging them due to concerns about how they are done, or was it purely just lack of time to review them?

My goal is to avoid completely hijacking the project and introducing stuff you're not comfortable with.

**Comment by mjackson** [comment]
I just closed the one PR because it seems out of scope for this plugin. Please feel free to merge your own and update deps as needed. When you're ready, I can do a `npm publish`.
