### ISSUE TITLE
can we publish 0.1.2 please?

### ISSUE THREAD

**Issue by mreinstein** [mjackson/rollup-plugin-url-resolve#13]
@mjackson I've pushed a few changes, the biggest one being a fix so that this module works correctly on windows.

Can you please pull the latest and run `npm publish` ?

Much thanks!

**Comment by mreinstein** [comment]
Or alternatively you could grant me publish access on npm. My name on npm is mreinstein as well.

**Comment by mjackson** [comment]
OK, I just added you as an owner to the npm package. Publish away!

-- Michael
