### ISSUE TITLE
Can't build because pointer to non-existing folder

### ISSUE THREAD

**Issue by JoviDeCroock** [mjackson/rollup-plugin-url-resolve#3]
In your index.js there is a pointer to a folder called cjs/ this isn't available in your published npm package: https://unpkg.com/rollup-plugin-url-resolve@0.1.0/

**Comment by mjackson** [comment]
This is fixed in 0.1.1, I just forgot to publish it. Please see https://unpkg.com/browse/rollup-plugin-url-resolve@0.1.1/
